-- migrations/0001_init.sql
-- WOGO booking backend — initial schema. SQLite dialect (Cloudflare D1).

CREATE TABLE routes (
  id          TEXT PRIMARY KEY,              -- slug, e.g. 'amsterdam', 'rotterdam-hidden-gems'
  name        TEXT NOT NULL,                 -- display name, e.g. "Rotterdam Route 2 · Hidden Gems"
  city        TEXT NOT NULL,                 -- 'Amsterdam' | 'Rotterdam' | 'Utrecht' | 'Groningen' | ...
  price_cents INTEGER NOT NULL,              -- price PER PERSON, in eurocents
  capacity    INTEGER NOT NULL DEFAULT 10,   -- seats per departure/timeslot (owner default: 10)
  max_party   INTEGER NOT NULL DEFAULT 6,    -- max guests in one single booking (owner default: 6)
  open_days   TEXT NOT NULL,                 -- JSON array of ISO weekday ints, Mon=1..Sun=7, e.g. "[4,5,6]"
  slots       TEXT NOT NULL,                 -- JSON array of "HH:MM" 24h strings, e.g. "[\"17:30\",\"18:00\"]"
  map_url     TEXT,                          -- route-map link sent in the 2nd guest email; NULL until owner fills it in
  active      INTEGER NOT NULL DEFAULT 1,    -- 1 = bookable, 0 = hidden everywhere (guest + admin still see history)
  created_at  TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE bookings (
  id                    TEXT PRIMARY KEY,           -- crypto.randomUUID(), generated by the Worker
  route_id              TEXT NOT NULL REFERENCES routes(id),
  date                  TEXT NOT NULL,              -- 'YYYY-MM-DD'
  slot                  TEXT NOT NULL,               -- 'HH:MM' 24h
  party                 INTEGER NOT NULL,             -- 1..route.max_party
  name                  TEXT NOT NULL,
  email                 TEXT NOT NULL,
  phone                 TEXT,
  locale                TEXT NOT NULL DEFAULT 'en',     -- 'en' | 'nl'
  marketing_opt_in      INTEGER NOT NULL DEFAULT 0,
  status                TEXT NOT NULL DEFAULT 'hold',     -- see status machine below
  stripe_session         TEXT,                             -- Checkout Session id (cs_...)
  stripe_payment_intent   TEXT,                              -- filled on confirm; used for refunds/CAPI
  created_at              TEXT NOT NULL DEFAULT (datetime('now')),
  hold_expires             TEXT                               -- ISO datetime; NULL once confirmed/cancelled
);

-- status machine: hold -> confirmed | expired | cancelled
--                 hold -> confirmed_conflict  (rare edge case, see SPEC.md §6.4)
-- 'hold' is the ONLY status that ever counts toward capacity together with 'confirmed'.

CREATE INDEX idx_bookings_avail   ON bookings (route_id, date, slot, status, hold_expires);
CREATE INDEX idx_bookings_session ON bookings (stripe_session);
CREATE INDEX idx_bookings_expiry  ON bookings (status, hold_expires);
CREATE INDEX idx_bookings_date    ON bookings (date);

CREATE TABLE routes_bars (
  id             INTEGER PRIMARY KEY AUTOINCREMENT,
  route_id       TEXT NOT NULL REFERENCES routes(id),
  ord            INTEGER NOT NULL,           -- stop order: 1, 2, 3...
  bar_name       TEXT NOT NULL,
  bar_email      TEXT NOT NULL,
  minutes_offset INTEGER NOT NULL DEFAULT 0  -- minutes after the booked slot time this bar expects guests
);

CREATE INDEX idx_routes_bars_route ON routes_bars (route_id, ord);

CREATE TABLE date_overrides (
  id        INTEGER PRIMARY KEY AUTOINCREMENT,
  route_id  TEXT NOT NULL REFERENCES routes(id),
  date      TEXT NOT NULL,                    -- 'YYYY-MM-DD'
  action    TEXT NOT NULL,                    -- 'closed' | 'alternate_bars' | 'extra_slot' | 'remove_slot' | 'capacity_override'
  payload   TEXT,                             -- JSON, meaning depends on action (see SPEC.md §7.4)
  UNIQUE(route_id, date, action)
);

CREATE INDEX idx_overrides_lookup ON date_overrides (route_id, date);

CREATE TABLE settings (
  k TEXT PRIMARY KEY,
  v TEXT
);

-- Addition beyond the owner's 5 named tables, required for correctness (owner requirement #4:
-- "dedupes retries"). Kept minimal — one row per Stripe event ID ever processed.
CREATE TABLE webhook_events (
  id           TEXT PRIMARY KEY,      -- Stripe event id, e.g. 'evt_1Nx...'
  type         TEXT NOT NULL,
  received_at  TEXT NOT NULL DEFAULT (datetime('now'))
);
