/* ==========================================================================
   Build step for the WOGO admin dashboard. Zero dependencies (Node only).
   Reads the three editable source files (admin.html / admin.css / admin.js)
   and emits two artefacts:

     1. src/admin/assets.js        — imported by the Worker; exports adminPage()
                                       returning one self-contained HTML doc.
     2. preview/admin.html         — the same UI + mock.js, openable via file://.

   Run:  node src/admin/build.mjs   (from the backend/ directory or anywhere)
   ========================================================================== */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const backend = join(here, "..", "..");

const html = readFileSync(join(here, "admin.html"), "utf8");
const css = readFileSync(join(here, "admin.css"), "utf8");
const js = readFileSync(join(here, "admin.js"), "utf8");
const mock = readFileSync(join(here, "mock.js"), "utf8");

// Prevent an accidental "</script>" inside JS from closing the tag early.
const guard = (s) => s.replace(/<\/script/gi, "<\\/script");

const HEAD = (title) => `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<meta name="robots" content="noindex, nofollow">
<title>${title}</title>`;

/* ---- 1. Worker asset module ---- */
const assets = `/* AUTO-GENERATED by src/admin/build.mjs — do not edit by hand.
   Edit admin.html / admin.css / admin.js and re-run:  node src/admin/build.mjs */

export const ADMIN_CSS = ${JSON.stringify(css)};
export const ADMIN_HTML = ${JSON.stringify(html)};
export const ADMIN_JS = ${JSON.stringify(guard(js))};

/** Full self-contained admin page (login + app), served by the Worker at /admin. */
export function adminPage() {
  return ${JSON.stringify(HEAD("WOGO Admin"))} +
    "\\n<style>" + ADMIN_CSS + "</style>\\n</head>\\n<body>\\n" +
    ADMIN_HTML +
    "\\n<script>" + ADMIN_JS + "</script>\\n</body>\\n</html>";
}

/** Convenience for the Worker router: a ready Response for /admin and /admin/login. */
export function adminResponse() {
  return new Response(adminPage(), {
    headers: {
      "content-type": "text/html; charset=utf-8",
      "cache-control": "no-store",
      "x-content-type-options": "nosniff"
    }
  });
}
`;
writeFileSync(join(here, "assets.js"), assets);

/* ---- 2. Standalone preview ---- */
const preview = `${HEAD("WOGO Admin — preview")}
<style>${css}</style>
</head>
<body>
${html}
<script>${guard(mock)}</script>
<script>${guard(js)}</script>
</body>
</html>
`;
writeFileSync(join(backend, "preview", "admin.html"), preview);

console.log("admin build ok →");
console.log("  src/admin/assets.js");
console.log("  preview/admin.html");
